services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: qrenuapi-app-prod
    environment:
      NODE_ENV: production
      PORT: 3004
      DB_HOST: shared-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: qrenuapi_prod
      REDIS_HOST: shared-redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      ZOHO_SMTP_USER: ${ZOHO_SMTP_USER}
      ZOHO_SMTP_PASSWORD: ${ZOHO_SMTP_PASSWORD}
      ZOHO_FROM_EMAIL: ${ZOHO_FROM_EMAIL}
      ZOHO_FROM_NAME: ${ZOHO_FROM_NAME}
      FRONTEND_URL: https://qrenu.com
    ports:
      - "3004:3004"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - shared-infrastructure_shared-network
      - tulukdev_tulukdev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared-infrastructure_shared-network:
    external: true
  tulukdev_tulukdev-network:
    external: true
