version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: qrenuapi-postgres-dev
    environment:
      POSTGRES_DB: qrenuapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - qrenuapi-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: qrenuapi-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - qrenuapi-network

  # QRenu API Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: qrenuapi-app-dev
    environment:
      NODE_ENV: development
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: qrenuapi
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: dev-jwt-secret-key-change-in-production
      JWT_EXPIRES_IN: 24h
      MAILERSEND_API_KEY: your-mailersend-api-key
      MAILERSEND_FROM_EMAIL: noreply@qrenu.com
      MAILERSEND_FROM_NAME: QRenu
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
      - ./uploads:/app/uploads
    depends_on:
      - postgres
      - redis
    networks:
      - qrenuapi-network
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  qrenuapi-network:
    driver: bridge
